name: PluginManager
version: 1.2.3-SNAPSHOT
author: obnoxint
authors: [obnoxint, Technius]
website: http://dev.bukkit.org/bukkit-plugins/pm-pluginmanager/
description: A plugin used for managing plugins
soft-depends: [PerWorldPlugins, MCore]
main: co.technius.PluginManager.PluginManagerPlugin
commands:
    pluginmanager:
        description: PluginManager commands
        usage: /pm <arguments>
        aliases: [plman, plm, pm]
permissions:
    pluginmanager.*:
        default: false
        description: Gives all PluginManager permissions
        children:
            pluginmanager.list: true
            pluginmanager.enable: true
            pluginmanager.disable: true
            pluginmanager.load: true
            pluginmanager.unload: true
            pluginmanager.reload: true
            pluginmanager.show: true
            pluginmanager.softreload: true
            pluginmanager.cmd.*: true
            pluginmanager.plugget.*: true
    pluginmanager.cmd.*:
        default: false
        description: Gives all PluginManager cmd permissions
        children:
            pluginmanager.cmd.unregister: true
            pluginmanager.cmd.priority: true
    pluginmanager.plugget.*:
        default: false
        description: Gives all PluginManager plug-get permissions
        children:
            pluginmanager.plugget.search: true
            pluginmanager.plugget.check: true
    pluginmanager.list:
        default: false
    pluginmanager.enable:
        default: false
    pluginmanager.disable:
        default: false
    pluginmanager.load:
        default: false
    pluginmanager.unload:
        default: false
    pluginmanager.reload:
        default: false
    pluginmanager.show:
        default: false
    pluginmanager.softreload:
        default: false
    pluginmanager.cmd.unregister:
        default: false
    pluginmanager.cmd.priority:
        default: false
    pluginmanager.plugget.search:
        default: false
    pluginmanager.plugget.check:
        default: false